From openjdk:11
copy /home/ubuntu/jars/loginCadastro/login-cadastro-bcd-0.0.1-SNAPSHOT.jar login-cadastro-bcd-0.0.1-SNAPSHOT.jar
CMD ["java","-jar","login-cadastro-bcd-0.0.1-SNAPSHOT.jar","--spring.profiles.active=prod"]
